print("EVALUAR SI NÚMERO MENOR QUE 100")
print("---")
print("Ingrese un número: ")
print("---")
x = int( input())
print("---")
print("\nSALIDA: ")
print("---")
if x<100 : print("El número es menor que 100")
else : print("El número es mayor que 100")
